/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Section } from "./Section";
import { SectionCountArgs } from "./SectionCountArgs";
import { SectionFindManyArgs } from "./SectionFindManyArgs";
import { SectionFindUniqueArgs } from "./SectionFindUniqueArgs";
import { CreateSectionArgs } from "./CreateSectionArgs";
import { UpdateSectionArgs } from "./UpdateSectionArgs";
import { DeleteSectionArgs } from "./DeleteSectionArgs";
import { TopicFindManyArgs } from "../../topic/base/TopicFindManyArgs";
import { Topic } from "../../topic/base/Topic";
import { SectionService } from "../section.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Section)
export class SectionResolverBase {
  constructor(
    protected readonly service: SectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Section",
    action: "read",
    possession: "any",
  })
  async _sectionsMeta(
    @graphql.Args() args: SectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Section])
  @nestAccessControl.UseRoles({
    resource: "Section",
    action: "read",
    possession: "any",
  })
  async sections(
    @graphql.Args() args: SectionFindManyArgs
  ): Promise<Section[]> {
    return this.service.sections(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Section, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Section",
    action: "read",
    possession: "own",
  })
  async section(
    @graphql.Args() args: SectionFindUniqueArgs
  ): Promise<Section | null> {
    const result = await this.service.section(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Section)
  @nestAccessControl.UseRoles({
    resource: "Section",
    action: "create",
    possession: "any",
  })
  async createSection(
    @graphql.Args() args: CreateSectionArgs
  ): Promise<Section> {
    return await this.service.createSection({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Section)
  @nestAccessControl.UseRoles({
    resource: "Section",
    action: "update",
    possession: "any",
  })
  async updateSection(
    @graphql.Args() args: UpdateSectionArgs
  ): Promise<Section | null> {
    try {
      return await this.service.updateSection({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Section)
  @nestAccessControl.UseRoles({
    resource: "Section",
    action: "delete",
    possession: "any",
  })
  async deleteSection(
    @graphql.Args() args: DeleteSectionArgs
  ): Promise<Section | null> {
    try {
      return await this.service.deleteSection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Topic], { name: "topics" })
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  async findTopics(
    @graphql.Parent() parent: Section,
    @graphql.Args() args: TopicFindManyArgs
  ): Promise<Topic[]> {
    const results = await this.service.findTopics(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
